import type { SkillGroup } from '@/types/content';

export const skills: SkillGroup[] = [
  { id: 'product', title: { da: 'Produkt & systemer', en: 'Product & systems' }, description: { da: 'Behovet bliver omsat til en tydelig løsning og et produkt, der kan drives.', en: 'Turning the need into a clear solution and a product that can be operated.' }, skills: ['Product discovery', 'Requirements', 'Process mapping', 'Technical product', 'System design', 'Data modelling', 'UX flows', 'QA', 'Release planning'] },
  { id: 'frontend', title: { da: 'Web & mobile', en: 'Web & mobile' }, description: { da: 'Hurtige, tilgængelige oplevelser til web, iOS og Android.', en: 'Fast, accessible experiences for web, iOS and Android.' }, skills: ['Next.js', 'React', 'Astro', 'React Native', 'Expo', 'TypeScript', 'HTML / CSS', 'Accessibility', 'Responsive UI', 'Native Swift'] },
  { id: 'backend', title: { da: 'Backend & data', en: 'Backend & data' }, description: { da: 'Datamodeller, API’er og adgangsstyring, som resten af produktet kan stole på.', en: 'Data models, APIs and access control the rest of the product can rely on.' }, skills: ['Node.js', 'PostgreSQL', 'SQLite', 'Firebase / NoSQL', 'REST APIs', 'Webhooks', 'Authentication', 'Authorisation', 'Data migrations'] },
  { id: 'infra', title: { da: 'Cloud & levering', en: 'Cloud & delivery' }, description: { da: 'Sikker deployment, performance og indsigt i det, der kører.', en: 'Secure deployment, performance and visibility into what is running.' }, skills: ['Cloudflare Workers', 'Pages', 'Storage', 'GitHub Actions', 'CI / CD', 'Logging', 'Monitoring', 'Performance', 'Security'] },
  { id: 'automation', title: { da: 'Integration & automation', en: 'Integration & automation' }, description: { da: 'Systemer og data forbundet, så manuelt arbejde og fejl bliver reduceret.', en: 'Connecting systems and data to reduce manual work and errors.' }, skills: ['API integration', 'REST integrations', 'Webhooks', 'Scheduled jobs', 'Workflow automation', 'Data validation', 'Data quality', 'AI-assisted workflows'] },
  { id: 'operations', title: { da: 'Drift & mennesker', en: 'Operations & people' }, description: { da: 'Teknisk ansvar tæt på brugere, kunder og den daglige forretning.', en: 'Technical ownership close to users, customers and day-to-day business.' }, skills: ['Technical support', 'Customer Success', 'Incident coordination', 'Troubleshooting', 'Key accounts', 'Documentation', 'Stakeholder management', 'Release support'] }
];
